name: Testing

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 3
      matrix:
        php: [ 8.0, 7.4, 7.3 ]
        dependency-version: [ prefer-stable ]

    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}
        extensions: xdebug
    - name: Install Dependencies
      run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
    - name: Execute tests (Unit and Feature)
      run: vendor/bin/phpunit --coverage-text
    - name: Static analysis with PHPStan
      run: vendor/bin/phpstan analyse
    - name: Coding style PSR12 Check
      run: vendor/bin/phpcs
